### ISSUE TITLE
Change 'Work' to 'How we work' in the nav bar

### ISSUE THREAD

**Issue by dajbelshaw** [weareopen/weareopen.github.io#13]
This page is mostly about how we work rather than who we work with or what we work on, so the title should probably reflect that?

**Comment by LauraHilliger** [comment]
Ah, it's not a bad idea, but if we're adding words to the Nav in one place, I'd recommend consistency. So, how about:

- About the co-op
- How we work
- Reflecting on projects (goes to blog.weareopen.coop)
- Support our stuff
