### ISSUE TITLE
resizing the browser moves bg images into font

### ISSUE THREAD

**Issue by annehilliger** [weareopen/weareopen.github.io#15]
when resizing the browser the background pattern moves into the font and the bottom image into the footer
![Screenshot-resizing](https://github.com/weareopen/weareopen.github.io/assets/98102348/a73b1a8a-4428-4677-9f63-c1357a3b18ee)

**Comment by LauraHilliger** [comment]
yeah, the top bit has font bg colour so that in-between browser sizes still have legible words. The bottom has been futzed with and futzt with, but not fixable. Issue resolves in mobile view with layout change.
