### ISSUE TITLE
Please change Annes picture

### ISSUE THREAD

**Issue by annehilliger** [weareopen/weareopen.github.io#18]
The one on the site is super old
I add the one that I want as a file to this issue. Hope this works

![IMG_5096-square](https://github.com/weareopen/weareopen.github.io/assets/98102348/157e6fcb-c525-43de-98ca-7bbf9d639d0b)

**Comment by LauraHilliger** [comment]
done. https://github.com/weareopen/weareopen.github.io/commit/09a1806ab9919f5667d95200d4bd4f8dbf30f4d1
