### ISSUE TITLE
Link to great blog posts about projects

### ISSUE THREAD

**Issue by LauraHilliger** [weareopen/weareopen.github.io#7]
Not sure how many or where to link, but these are good:

https://blog.weareopen.coop/steps-to-success-when-building-a-community-of-practice-15bd7ed9ac5c
https://blog.weareopen.coop/navigating-greenpeaces-critical-incident-network-5d9fe79ea824
https://blog.weareopen.coop/the-art-of-community-cultivating-online-connections-738cc90b0a39

Which ones do you want to point to??

**Comment by dajbelshaw** [comment]
I like this idea instead of having a 'write up' for each client on the website. I wonder if we can collect them somehow so we can link to a number of posts? I'm not sure Medium allows us to categorise/tag all of the Greenpeace blog posts, for example?

**Comment by LauraHilliger** [comment]
SOLVED with the new section in our wiki: https://wiki.weareopen.coop/en/clients/overview
