### ISSUE TITLE
Improve padding around text

### ISSUE THREAD

**Issue by dajbelshaw** [weareopen/weareopen.github.io#8]
![image](https://github.com/weareopen/weareopen.github.io/assets/2429426/dc45a9fe-57e9-43b8-be9a-5f8d96bfe381)

At tablet size or non-full-desktop screensize there's some weirdness. Looks fine on mobile, though!

**Comment by LauraHilliger** [comment]
Please see comments on https://github.com/weareopen/weareopen.github.io/issues/15
